#!/usr/bin/env bash

uv run extract_features --video data/Fold1_part1/03/10.mov --subject 03 --label 10 --out features
uv run extract_features --video data/Fold1_part1/04/0.mp4 --subject 04 --label 0 --out features
uv run extract_features --video data/Fold1_part1/04/5.mp4 --subject 04 --label 5 --out features
uv run extract_features --video data/Fold1_part1/04/10.mp4 --subject 04 --label 10 --out features
uv run extract_features --video data/Fold1_part1/05/0.MOV --subject 05 --label 0 --out features
uv run extract_features --video data/Fold1_part1/05/5.MOV --subject 05 --label 5 --out features
uv run extract_features --video data/Fold1_part1/05/10.MOV --subject 05 --label 10 --out features
uv run extract_features --video data/Fold1_part1/06/0.mp4 --subject 06 --label 0 --out features
uv run extract_features --video data/Fold1_part1/06/5.mp4 --subject 06 --label 5 --out features
uv run extract_features --video data/Fold1_part1/06/10.mp4 --subject 06 --label 10 --out features
uv run extract_features --video data/Fold1_part2/07/0.mp4 --subject 07 --label 0 --out features
uv run extract_features --video data/Fold1_part2/07/5.mp4 --subject 07 --label 5 --out features
uv run extract_features --video data/Fold1_part2/07/10.mp4 --subject 07 --label 10 --out features
uv run extract_features --video data/Fold1_part2/08/0.mp4 --subject 08 --label 0 --out features
uv run extract_features --video data/Fold1_part2/08/5.mp4 --subject 08 --label 5 --out features
uv run extract_features --video data/Fold1_part2/08/10.mp4 --subject 08 --label 10 --out features
uv run extract_features --video data/Fold1_part2/09/0.mp4 --subject 09 --label 0 --out features
uv run extract_features --video data/Fold1_part2/09/5.mp4 --subject 09 --label 5 --out features
uv run extract_features --video data/Fold1_part2/09/10.mp4 --subject 09 --label 10 --out features
uv run extract_features --video data/Fold1_part2/10/0.MOV --subject 10 --label 0 --out features
uv run extract_features --video data/Fold1_part2/10/5.MOV --subject 10 --label 5 --out features
uv run extract_features --video data/Fold1_part2/10/10.MOV --subject 10 --label 10 --out features
uv run extract_features --video data/Fold1_part2/11/0.mp4 --subject 11 --label 0 --out features
uv run extract_features --video data/Fold1_part2/11/5.mp4 --subject 11 --label 5 --out features
uv run extract_features --video data/Fold1_part2/11/10.mp4 --subject 11 --label 10 --out features
uv run extract_features --video data/Fold1_part2/12/0.mp4 --subject 12 --label 0 --out features
uv run extract_features --video data/Fold1_part2/12/5.mp4 --subject 12 --label 5 --out features
uv run extract_features --video data/Fold1_part2/12/10.mp4 --subject 12 --label 10 --out features
uv run extract_features --video data/Fold2_part1/13/0.mp4 --subject 13 --label 0 --out features
uv run extract_features --video data/Fold2_part1/13/5.mp4 --subject 13 --label 5 --out features
uv run extract_features --video data/Fold2_part1/13/10.mp4 --subject 13 --label 10 --out features
uv run extract_features --video data/Fold2_part1/14/0.mp4 --subject 14 --label 0 --out features
uv run extract_features --video data/Fold2_part1/14/5.mp4 --subject 14 --label 5 --out features
uv run extract_features --video data/Fold2_part1/14/10.mp4 --subject 14 --label 10 --out features
uv run extract_features --video data/Fold2_part1/15/0.mp4 --subject 15 --label 0 --out features
uv run extract_features --video data/Fold2_part1/15/5.mp4 --subject 15 --label 5 --out features
uv run extract_features --video data/Fold2_part1/15/10.mp4 --subject 15 --label 10 --out features
uv run extract_features --video data/Fold2_part1/16/0.MOV --subject 16 --label 0 --out features
uv run extract_features --video data/Fold2_part1/16/5.MOV --subject 16 --label 5 --out features
uv run extract_features --video data/Fold2_part1/16/10.MOV --subject 16 --label 10 --out features
uv run extract_features --video data/Fold2_part1/17/0.mp4 --subject 17 --label 0 --out features
uv run extract_features --video data/Fold2_part1/17/5.mp4 --subject 17 --label 5 --out features
uv run extract_features --video data/Fold2_part1/17/10.mp4 --subject 17 --label 10 --out features
uv run extract_features --video data/Fold2_part1/18/0.mov --subject 18 --label 0 --out features
uv run extract_features --video data/Fold2_part1/18/5.mov --subject 18 --label 5 --out features
uv run extract_features --video data/Fold2_part1/18/10.mov --subject 18 --label 10 --out features